name = "ViscoAnalysis"
uuid = "f3907c9a-3bd0-4f55-a1d0-a45fef2425d9"
authors = ["Bernus Kouevidjin"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
